# netlify.toml
[build]
  # Directory to run the build command in
  publish = "build"

  # Command to build your site
  command = "npm run build"

# Functions settings
[build.functions]
  # Directory where Netlify will look for your serverless functions
  directory = "functions"
